(packages->manifest
 (list
  ;; (specification->package "python")
  ;; (specification->package "mesa")
  ;; (specification->package "pciutils")
  ;; (specification->package "alsa-lib")
  ;; (specification->package "libsm")
  ;; (specification->package "libxcomposite")
  ;; (specification->package "libxrandr")
  ;; (specification->package "libxrender")
  ;; (specification->package "libxtst")
  ;; (specification->package "xcb-util-wm")
  ;; (specification->package "xcb-util-image")
  ;; (specification->package "xcb-util-keysyms")
  ;; (specification->package "xcb-util-renderutil")
  (specification->package "conda")))
