# -*- sh -*-
################################################################################
# Terminate shepherd user services
################################################################################

services=$(herd status | grep '+' | sed 's/\+//' | tr -d ' ')
for s in ${services[@]}; do
    herd stop "$s"
done
